config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "musics#index"
  resources :musics do
    resources :comments, only: [:create]
  end
  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :text, presence: true

  belongs_to :user
  belongs_to :music
end

app/models/music.rb
class Music < ApplicationRecord
  with_options presence: true do
    validates :title
    validates :artist
    validates :image
    validates :audio
    validates :introduction
  end

  mount_uploader :audio, AudioUploader

  belongs_to :user
  has_one_attached :image
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z+\d]+\z/i.freeze

  validates :nickname, presence: true, length: { maximum: 6 }
  validates :password, format: { with: VALID_PASSWORD_REGEX, message: 'は半角英数字混合で入力してください' }

  has_many :musics
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['BASIC_AUTH_USER'] && password == ENV['BASIC_AUTH_PASSWORD']
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to music_path(@comment.music)
    else
      @music = @comment.music
      @comments = @music.comments
      render 'musics/show'
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, music_id: params[:music_id])
  end
end

app/controllers/musics_controller.rb
class MusicsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :show]
  before_action :set_music, only: [:show, :edit, :update]

  def index
    @musics = Music.page(params[:page]).per(6).includes(:user).order('created_at DESC')
  end

  def new
    @music = Music.new
  end

  def create
    @music = Music.new(music_params)
    @music.user_id = current_user.id
    if @music.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @music.comments.includes(:user).order('created_at DESC')
  end

  def edit
    redirect_to action: :index unless @music.user_id == current_user.id
  end

  def update
    @music.user_id = current_user.id
    if @music.update(music_params)
      redirect_to music_path
    else
      render :edit
    end
  end

  def destroy
    music = Music.find(params[:id])
    music.user_id = current_user.id
    music.destroy
    redirect_to root_path
  end

  private

  def music_params
    params.require(:music).permit(:title, :artist, :image, :audio, :introduction).merge(user_id: current_user.id)
  end

  def set_music
    @music = Music.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @musics = @user.musics.order('created_at DESC')
    @musics = Kaminari.paginate_array(@musics).page(params[:page]).per(6)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>LikeMusic</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= link_to image_tag("logo.png", class: :logo), root_path %>
          </div>
          <% if user_signed_in? %>
            <div class="nav__right"> 
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "btn btn-outline-secondary" %>
              <%= link_to "New Music", new_music_path, class: "btn btn-outline-primary" %>
            </div> 
          <% else %>
            <div class="nav__right">
              <%= link_to "ログイン", new_user_session_path, class: "btn btn-outline-primary" %>
              <%= link_to "新規登録", new_user_registration_path, class: "btn btn-outline-primary" %>
            </div>
          <% end %>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p class="copyright">Copyright © LIKE MUSIC All rights reserved.</p>
    </footer>
  </body>
</html>

app/views/musics/_form.html.erb
<%= form_with(model: music, local: true) do |f|%>

  <%= render 'shared/error_messages', model: f.object %>

  <div class="field">
    <%= f.label :title, "タイトル" %><br />
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :artist, "アーティスト" %><br />
    <%= f.text_field :artist %>
  </div>

  <div class="field">
    <%= f.label :image, "イメージ画像" %><br />
    <%= f.file_field :image, id:"music-image" %>
  </div>
  <div id="image-list"></div>

  <div class="field">
    <%= f.label :audio, "mp3 file" %><br />
    <%= f.file_field :audio %>
  </div>

  <div class="field">
    <%= f.label :introduction, "曲紹介" %><br />
    <%= f.text_area :introduction, class: :form__text %>
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: "btn btn-outline-success" %>
  </div>
<% end %>

app/views/musics/_music.html.erb
<div class="card">
  <div class="card__body">
    <%= link_to music.title, music_path(music.id), class: :card__title%>
    <p class="card__summary">
      <%= music.artist %>
    </p>
    <%= link_to "by #{music.user.nickname}" , "/users/#{music.user.id}", class: :card__user %>
  </div>
  <%= link_to (image_tag music.image.variant(resize: '500x500')if music.image.attached?), music_path(music.id), class: :card__img %>
</div>

app/views/musics/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">音楽情報編集</h2>
      <%= render partial: "form", locals: { music: @music } %>
    </div>
  </div>
</div>

app/views/musics/index.html.erb
<main class="main">
  <div class="inner">
    <% if user_signed_in? %>
    <div class="greeting">
      <%= "ようこそ" %>
      <%= link_to "#{current_user.nickname}さん", "/users/#{current_user.id}", class: "btn btn-link" %>
    </div> 
    <% end %>
    <div class="card__wrapper">
      <%= render partial: 'music', collection: @musics %>
    </div>
  </div>
</main>
<%= paginate(@musics) %>

app/views/musics/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">新規音楽投稿</h2>
        <%= render partial: "form", locals: { music: @music } %>
    </div>
  </div>
</div>

app/views/musics/show.html.erb
<main class="main">
  <div class="inner">
    <div class="prototype__wrapper">
      <p class="prototype__hedding">
        <%= @music.title %>
      </p>
      <p class="prototype__hedding">
        <%= @music.artist %>
      </p>
      <%= link_to "by #{@music.user.nickname}" , "/users/#{@music.user.id}", class: :prototype__user %>
      <% if user_signed_in? && current_user.id == @music.user_id %>
        <div class="prototype__manage">
          <%= link_to "編集する", edit_music_path(@music.id), class: "btn btn-outline-info" %>
          <%= link_to "削除する", music_path(@music.id), method: :delete, class: "btn btn-outline-danger" %>
        </div>
      <% end %>
      <div class="prototype__image">
        <%= image_tag @music.image.variant(resize: '500x500')if @music.image.attached? %>
      </div>
      <div class="prototype__body">
        <div class="prototype__detail">
          <p class="detail__title">曲紹介</p>
          <p class="detail__message">
            <%= @music.introduction %>
          </p>
        </div>
      </div>
      <audio src= "<%= "#{@music.audio}" %>" controls="">
        <a src="<%= "#{@music.audio}" %>">ダウンロード</a>
      </audio>
      <div class="prototype__comments">
        <% if user_signed_in? %>
          <%= form_with(model: [@music, @comment], local: true) do |f|%>
            <div class="field">
              <%= f.label :text, "コメント" %><br />
              <%= f.text_field :text %>
            </div>
            <div class="actions">
              <%= f.submit "送信する", class: "btn btn-outline-info" %>
            </div>
          <% end %> 
        <% end %> 
        <ul class="comments_lists">
          <% if @comments %>
            <% @comments.each do |comment| %>
            <li class="comments_list">
              <%= comment.text %>
              <strong><%= link_to comment.user.nickname, "/users/#{comment.user.id}", class: "btn btn-link" %></strong>
            </li>
            <% end %>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</main>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/users/show.html.erb
<div class="main">
  <div class="inner">
    <div class="user__wrapper">
      <h2 class="page-heading">
        <%= "#{@user.nickname}さんの音楽" %>
      </h2>
      <div class="user__card">
        <%= render partial: 'musics/music', collection: @musics %>
      </div>
    </div>
  </div>
</div>
<%= paginate(@musics) %>